package task

type TaskProgressState int

const (
	None TaskProgressState = iota
	TaskPause
	TaskDoing
	TaskUploadFileMakeSlice
	TaskUploadFileMakeSliceDone
	TaskUploadFilePaying
	TaskUploadFilePayingDone
	TaskUploadFileCommitWhitelist
	TaskUploadFileCommitWhitelistDone
	TaskUploadFileFindReceivers
	TaskUploadFileFindReceiversDone
	TaskUploadFileGeneratePDPData
	TaskUploadFileTransferBlocks
	TaskUploadFileTransferBlocksDone
	TaskUploadFileWaitForPDPProve
	TaskUploadFileWaitForPDPProveDone
	TaskUploadFileRegisterDNS
	TaskUploadFileRegisterDNSDone
	TaskDownloadFileStart
	TaskDownloadFileDownloading
	TaskDownloadFileMakeSeed
)
