// Code generated by protoc-gen-go. DO NOT EDIT.
// source: progress.proto

package progress

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProgressInfo struct {
	WalletAddr           string   `protobuf:"bytes,1,opt,name=walletAddr,proto3" json:"walletAddr,omitempty"`
	NodeAddr             string   `protobuf:"bytes,2,opt,name=nodeAddr,proto3" json:"nodeAddr,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProgressInfo) Reset()         { *m = ProgressInfo{} }
func (m *ProgressInfo) String() string { return proto.CompactTextString(m) }
func (*ProgressInfo) ProtoMessage()    {}
func (*ProgressInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_progress_91455a5723f7ffa4, []int{0}
}
func (m *ProgressInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProgressInfo.Unmarshal(m, b)
}
func (m *ProgressInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProgressInfo.Marshal(b, m, deterministic)
}
func (dst *ProgressInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProgressInfo.Merge(dst, src)
}
func (m *ProgressInfo) XXX_Size() int {
	return xxx_messageInfo_ProgressInfo.Size(m)
}
func (m *ProgressInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProgressInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProgressInfo proto.InternalMessageInfo

func (m *ProgressInfo) GetWalletAddr() string {
	if m != nil {
		return m.WalletAddr
	}
	return ""
}

func (m *ProgressInfo) GetNodeAddr() string {
	if m != nil {
		return m.NodeAddr
	}
	return ""
}

func (m *ProgressInfo) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Progress struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash                 string          `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Operation            int32           `protobuf:"varint,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Sender               string          `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Infos                []*ProgressInfo `protobuf:"bytes,5,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Progress) Reset()         { *m = Progress{} }
func (m *Progress) String() string { return proto.CompactTextString(m) }
func (*Progress) ProtoMessage()    {}
func (*Progress) Descriptor() ([]byte, []int) {
	return fileDescriptor_progress_91455a5723f7ffa4, []int{1}
}
func (m *Progress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Progress.Unmarshal(m, b)
}
func (m *Progress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Progress.Marshal(b, m, deterministic)
}
func (dst *Progress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Progress.Merge(dst, src)
}
func (m *Progress) XXX_Size() int {
	return xxx_messageInfo_Progress.Size(m)
}
func (m *Progress) XXX_DiscardUnknown() {
	xxx_messageInfo_Progress.DiscardUnknown(m)
}

var xxx_messageInfo_Progress proto.InternalMessageInfo

func (m *Progress) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Progress) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Progress) GetOperation() int32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func (m *Progress) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Progress) GetInfos() []*ProgressInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func init() {
	proto.RegisterType((*ProgressInfo)(nil), "progress.ProgressInfo")
	proto.RegisterType((*Progress)(nil), "progress.Progress")
}

func init() { proto.RegisterFile("progress.proto", fileDescriptor_progress_91455a5723f7ffa4) }

var fileDescriptor_progress_91455a5723f7ffa4 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x6a, 0x85, 0x30,
	0x18, 0x84, 0x89, 0x1a, 0xd1, 0xbf, 0xc5, 0xc5, 0x4f, 0x91, 0x50, 0x4a, 0x11, 0x57, 0x2e, 0x8a,
	0x8b, 0xf6, 0x04, 0x5d, 0x76, 0x57, 0x3c, 0x41, 0x6d, 0x13, 0x6b, 0x40, 0xf2, 0x4b, 0x92, 0xd2,
	0x7b, 0xbc, 0x13, 0x3f, 0x88, 0xd1, 0xe7, 0x6e, 0xbe, 0x99, 0x64, 0xc2, 0x04, 0xaa, 0xd5, 0xd2,
	0xaf, 0x55, 0xce, 0xf5, 0xab, 0x25, 0x4f, 0x58, 0xec, 0xdc, 0x7e, 0xc1, 0xfd, 0x67, 0xd4, 0x1f,
	0x66, 0x22, 0x7c, 0x06, 0xf8, 0x1f, 0x97, 0x45, 0xf9, 0x77, 0x29, 0xad, 0x60, 0x0d, 0xeb, 0xca,
	0xe1, 0xe4, 0xe0, 0x23, 0x14, 0x86, 0xa4, 0x0a, 0x69, 0x12, 0xd2, 0x83, 0xf1, 0x01, 0xf8, 0x0f,
	0xfd, 0x19, 0x2f, 0xd2, 0x86, 0x75, 0x7c, 0xd8, 0xa0, 0xbd, 0x30, 0x28, 0xf6, 0x27, 0xb0, 0x82,
	0x44, 0xcb, 0x58, 0x9b, 0x68, 0x89, 0x08, 0xd9, 0x3c, 0xba, 0x39, 0x56, 0x05, 0x8d, 0x4f, 0x50,
	0xd2, 0xaa, 0xec, 0xe8, 0x35, 0x99, 0x58, 0x75, 0x33, 0xb0, 0x86, 0xdc, 0x29, 0x23, 0x95, 0x15,
	0x59, 0xb8, 0x13, 0x09, 0x5f, 0x80, 0x6b, 0x33, 0x91, 0x13, 0xbc, 0x49, 0xbb, 0xbb, 0xd7, 0xba,
	0x3f, 0x26, 0x9f, 0xf7, 0x0d, 0xdb, 0xa1, 0xef, 0x3c, 0xfc, 0xc3, 0xdb, 0x35, 0x00, 0x00, 0xff,
	0xff, 0x92, 0x79, 0x3c, 0xd6, 0x19, 0x01, 0x00, 0x00,
}
