// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dsp_message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	MsgLength            int32    `protobuf:"varint,3,opt,name=msgLength,proto3" json:"msgLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd5edefc259b45b9, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Header) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Header) GetMsgLength() int32 {
	if m != nil {
		return m.MsgLength
	}
	return 0
}

type Error struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd5edefc259b45b9, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Signature struct {
	SigData              []byte   `protobuf:"bytes,1,opt,name=sigData,proto3" json:"sigData,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd5edefc259b45b9, []int{2}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSigData() []byte {
	if m != nil {
		return m.SigData
	}
	return nil
}

func (m *Signature) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type Message struct {
	MsgId                string     `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Syn                  string     `protobuf:"bytes,2,opt,name=syn,proto3" json:"syn,omitempty"`
	Header               *Header    `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Data                 []byte     `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Sig                  *Signature `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
	Error                *Error     `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd5edefc259b45b9, []int{3}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *Message) GetSyn() string {
	if m != nil {
		return m.Syn
	}
	return ""
}

func (m *Message) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *Message) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "pb.Header")
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*Signature)(nil), "pb.Signature")
	proto.RegisterType((*Message)(nil), "pb.Message")
}

func init() { proto.RegisterFile("dsp_message.proto", fileDescriptor_cd5edefc259b45b9) }

var fileDescriptor_cd5edefc259b45b9 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x25, 0x4d, 0x93, 0x92, 0xb1, 0x05, 0x1d, 0x3c, 0xec, 0x41, 0x68, 0xc9, 0xa9, 0xa7, 0x1c,
	0x14, 0xbf, 0x40, 0x05, 0x45, 0xbd, 0xac, 0xde, 0x25, 0x69, 0x86, 0x6d, 0xc0, 0x24, 0xcb, 0x6e,
	0x2a, 0xe4, 0x9b, 0xfc, 0x49, 0x99, 0xc9, 0xc6, 0xde, 0x66, 0xde, 0xce, 0x7b, 0x6f, 0xe6, 0x2d,
	0x5c, 0xd5, 0xde, 0x7e, 0xb5, 0xe4, 0x7d, 0x69, 0xa8, 0xb0, 0xae, 0x1f, 0x7a, 0x5c, 0xd8, 0x2a,
	0xff, 0x84, 0xf4, 0x99, 0xca, 0x9a, 0x1c, 0x2a, 0x58, 0xfd, 0x90, 0xf3, 0x4d, 0xdf, 0xa9, 0x68,
	0x17, 0xed, 0x33, 0x3d, 0xb7, 0x88, 0xb0, 0x1c, 0x46, 0x4b, 0x6a, 0x21, 0xb0, 0xd4, 0x78, 0x03,
	0x59, 0xeb, 0xcd, 0x1b, 0x75, 0x66, 0x38, 0xaa, 0x78, 0x17, 0xed, 0x13, 0x7d, 0x06, 0xf2, 0x7b,
	0x48, 0x9e, 0x9c, 0xeb, 0x1d, 0x53, 0x0f, 0x7d, 0x4d, 0xa2, 0xb8, 0xd1, 0x52, 0xb3, 0x51, 0xd8,
	0x23, 0x28, 0xce, 0x6d, 0xfe, 0x00, 0xd9, 0x47, 0x63, 0xba, 0x72, 0x38, 0x39, 0x19, 0xf3, 0x8d,
	0x79, 0x2c, 0x87, 0x52, 0xd8, 0x6b, 0x3d, 0xb7, 0xec, 0x6d, 0x4f, 0xd5, 0x77, 0x73, 0x78, 0xa5,
	0x51, 0x24, 0xd6, 0xfa, 0x0c, 0xe4, 0xbf, 0x11, 0xac, 0xde, 0x27, 0x41, 0xbc, 0x86, 0xa4, 0xf5,
	0xe6, 0xa5, 0x0e, 0x17, 0x4d, 0x0d, 0x5e, 0x42, 0xec, 0xc7, 0x2e, 0x98, 0x73, 0x89, 0x39, 0xa4,
	0x47, 0x49, 0x41, 0x4e, 0xb9, 0xb8, 0x85, 0xc2, 0x56, 0xc5, 0x94, 0x8b, 0x0e, 0x2f, 0x7c, 0x4a,
	0xcd, 0xcb, 0x2c, 0xc5, 0x50, 0x6a, 0xdc, 0x42, 0xec, 0x1b, 0xa3, 0x12, 0x21, 0x6d, 0x98, 0xf4,
	0xbf, 0xbf, 0xe6, 0x17, 0xdc, 0x42, 0x42, 0x1c, 0x84, 0x4a, 0x65, 0x24, 0xe3, 0x11, 0x49, 0x46,
	0x4f, 0x78, 0x95, 0xca, 0x57, 0xdc, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x09, 0xe8, 0xa0, 0x99,
	0x9f, 0x01, 0x00, 0x00,
}
