// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	MsgLength            int32    `protobuf:"varint,3,opt,name=msgLength,proto3" json:"msgLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f4396ec084d07bd8, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Header) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Header) GetMsgLength() int32 {
	if m != nil {
		return m.MsgLength
	}
	return 0
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f4396ec084d07bd8, []int{1}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Message struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f4396ec084d07bd8, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "pb.Header")
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*Message)(nil), "pb.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_f4396ec084d07bd8) }

var fileDescriptor_message_f4396ec084d07bd8 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xb1, 0x8e, 0x83, 0x30,
	0x10, 0x44, 0x05, 0x77, 0x06, 0xb1, 0xdc, 0x35, 0xae, 0x5c, 0x9c, 0x74, 0xc8, 0x15, 0x15, 0x05,
	0x51, 0x3e, 0x21, 0x52, 0x8a, 0xa4, 0xb1, 0xf2, 0x03, 0x76, 0x58, 0x41, 0x0a, 0xb0, 0x65, 0x5b,
	0x91, 0xf2, 0xf7, 0x91, 0x17, 0x50, 0xba, 0xd9, 0xb1, 0x66, 0xe6, 0x19, 0x7e, 0x67, 0x0c, 0x41,
	0x8f, 0xd8, 0x39, 0x6f, 0xa3, 0xe5, 0xb9, 0x33, 0xf2, 0x06, 0xc5, 0x19, 0xf5, 0x80, 0x9e, 0x0b,
	0x28, 0x9f, 0xe8, 0xc3, 0xc3, 0x2e, 0x22, 0x6b, 0xb2, 0xb6, 0x52, 0xfb, 0xc9, 0x39, 0x7c, 0xc7,
	0x97, 0x43, 0x91, 0x93, 0x4d, 0x9a, 0xff, 0x41, 0x35, 0x87, 0xf1, 0x82, 0xcb, 0x18, 0x27, 0xf1,
	0xd5, 0x64, 0x2d, 0x53, 0x1f, 0x43, 0x1e, 0x81, 0x9d, 0xbc, 0xb7, 0x3e, 0x45, 0xef, 0x76, 0x40,
	0x6a, 0x64, 0x8a, 0x74, 0x1a, 0xda, 0x38, 0xb6, 0xc6, 0xfd, 0x94, 0x06, 0xca, 0xeb, 0x2a, 0xb9,
	0x84, 0x62, 0x22, 0x2e, 0x8a, 0xd6, 0x3d, 0x74, 0xce, 0x74, 0x2b, 0xa9, 0xda, 0x5e, 0x52, 0xf9,
	0xa0, 0xa3, 0xa6, 0x96, 0x1f, 0x45, 0x9a, 0xff, 0x03, 0xc3, 0xb4, 0x4c, 0x4c, 0x75, 0x5f, 0xa5,
	0x18, 0xa1, 0xa8, 0xd5, 0x37, 0x05, 0xfd, 0xfd, 0xf0, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x08, 0x25,
	0xed, 0x7f, 0x0c, 0x01, 0x00, 0x00,
}
