// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package file

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Payment struct {
	WalletAddress        string   `protobuf:"bytes,1,opt,name=walletAddress,proto3" json:"walletAddress,omitempty"`
	Asset                int32    `protobuf:"varint,2,opt,name=asset,proto3" json:"asset,omitempty"`
	UnitPrice            uint64   `protobuf:"varint,3,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_bf34cc5ceb60cc03, []int{0}
}
func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (dst *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(dst, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

func (m *Payment) GetAsset() int32 {
	if m != nil {
		return m.Asset
	}
	return 0
}

func (m *Payment) GetUnitPrice() uint64 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

type Tx struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height               uint64   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_bf34cc5ceb60cc03, []int{1}
}
func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (dst *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(dst, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Tx) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Breakpoint struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Breakpoint) Reset()         { *m = Breakpoint{} }
func (m *Breakpoint) String() string { return proto.CompactTextString(m) }
func (*Breakpoint) ProtoMessage()    {}
func (*Breakpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_bf34cc5ceb60cc03, []int{2}
}
func (m *Breakpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Breakpoint.Unmarshal(m, b)
}
func (m *Breakpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Breakpoint.Marshal(b, m, deterministic)
}
func (dst *Breakpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Breakpoint.Merge(dst, src)
}
func (m *Breakpoint) XXX_Size() int {
	return xxx_messageInfo_Breakpoint.Size(m)
}
func (m *Breakpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Breakpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Breakpoint proto.InternalMessageInfo

func (m *Breakpoint) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Breakpoint) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type File struct {
	SessionId            string      `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Hash                 string      `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	BlockHashes          []string    `protobuf:"bytes,3,rep,name=blockHashes,proto3" json:"blockHashes,omitempty"`
	Operation            int32       `protobuf:"varint,4,opt,name=operation,proto3" json:"operation,omitempty"`
	Prefix               string      `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
	ChunkSize            int32       `protobuf:"varint,6,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	PayInfo              *Payment    `protobuf:"bytes,7,opt,name=payInfo,proto3" json:"payInfo,omitempty"`
	Tx                   *Tx         `protobuf:"bytes,8,opt,name=tx,proto3" json:"tx,omitempty"`
	Breakpoint           *Breakpoint `protobuf:"bytes,9,opt,name=breakpoint,proto3" json:"breakpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_bf34cc5ceb60cc03, []int{3}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *File) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *File) GetBlockHashes() []string {
	if m != nil {
		return m.BlockHashes
	}
	return nil
}

func (m *File) GetOperation() int32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func (m *File) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *File) GetChunkSize() int32 {
	if m != nil {
		return m.ChunkSize
	}
	return 0
}

func (m *File) GetPayInfo() *Payment {
	if m != nil {
		return m.PayInfo
	}
	return nil
}

func (m *File) GetTx() *Tx {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *File) GetBreakpoint() *Breakpoint {
	if m != nil {
		return m.Breakpoint
	}
	return nil
}

func init() {
	proto.RegisterType((*Payment)(nil), "file.Payment")
	proto.RegisterType((*Tx)(nil), "file.Tx")
	proto.RegisterType((*Breakpoint)(nil), "file.Breakpoint")
	proto.RegisterType((*File)(nil), "file.File")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_file_bf34cc5ceb60cc03) }

var fileDescriptor_file_bf34cc5ceb60cc03 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0xa5, 0x5d, 0xbb, 0xad, 0x77, 0x0c, 0x24, 0x0c, 0xc9, 0x83, 0x0f, 0xa5, 0x08, 0xf6, 0x69,
	0x0c, 0x05, 0xdf, 0xf5, 0x41, 0xdc, 0xdb, 0x88, 0xfb, 0x03, 0x59, 0x7b, 0x67, 0xc3, 0x6a, 0x52,
	0x9a, 0x0c, 0x3b, 0xff, 0x8e, 0x7f, 0x54, 0x9a, 0xc4, 0x75, 0x82, 0x6f, 0xf7, 0x9c, 0x9c, 0x73,
	0xc8, 0xfd, 0x00, 0xd8, 0x8b, 0x1a, 0x97, 0x4d, 0xab, 0x8c, 0x22, 0x51, 0x5f, 0x67, 0x05, 0x4c,
	0x36, 0xfc, 0xf4, 0x81, 0xd2, 0x90, 0x5b, 0x98, 0x7f, 0xf2, 0xba, 0x46, 0xf3, 0x54, 0x96, 0x2d,
	0x6a, 0x4d, 0x83, 0x34, 0xc8, 0x13, 0xf6, 0x97, 0x24, 0x0b, 0x88, 0xb9, 0xd6, 0x68, 0x68, 0x98,
	0x06, 0x79, 0xcc, 0x1c, 0x20, 0x37, 0x90, 0x1c, 0xa5, 0x30, 0x9b, 0x56, 0x14, 0x48, 0x47, 0x69,
	0x90, 0x47, 0x6c, 0x20, 0xb2, 0x15, 0x84, 0xdb, 0x8e, 0x10, 0x88, 0x2a, 0xae, 0x2b, 0x1f, 0x6b,
	0x6b, 0x72, 0x0d, 0xe3, 0x0a, 0xc5, 0x7b, 0xe5, 0xe2, 0x22, 0xe6, 0x51, 0xf6, 0x08, 0xf0, 0xdc,
	0x22, 0x3f, 0x34, 0x4a, 0x48, 0xf3, 0xaf, 0x73, 0x01, 0xb1, 0x90, 0x25, 0x76, 0xde, 0xe8, 0x40,
	0xf6, 0x1d, 0x42, 0xf4, 0x22, 0x6a, 0xec, 0x3f, 0xa4, 0x51, 0x6b, 0xa1, 0xe4, 0xba, 0xf4, 0xbe,
	0x81, 0x38, 0x07, 0x86, 0x17, 0x81, 0x29, 0xcc, 0x76, 0xb5, 0x2a, 0x0e, 0xaf, 0x5c, 0x57, 0xa8,
	0xe9, 0x28, 0x1d, 0xe5, 0x09, 0xbb, 0xa4, 0xfa, 0x4c, 0xd5, 0x60, 0xcb, 0x8d, 0x50, 0x92, 0x46,
	0xb6, 0xfd, 0x81, 0xe8, 0x5b, 0x69, 0x5a, 0xdc, 0x8b, 0x8e, 0xc6, 0x36, 0xd5, 0xa3, 0xde, 0x55,
	0x54, 0x47, 0x79, 0x78, 0x13, 0x5f, 0x48, 0xc7, 0xce, 0x75, 0x26, 0xc8, 0x1d, 0x4c, 0x1a, 0x7e,
	0x5a, 0xcb, 0xbd, 0xa2, 0x93, 0x34, 0xc8, 0x67, 0xf7, 0xf3, 0xa5, 0xdd, 0x91, 0x5f, 0x0a, 0xfb,
	0x7d, 0x25, 0x14, 0x42, 0xd3, 0xd1, 0xa9, 0xd5, 0x4c, 0x9d, 0x66, 0xdb, 0xb1, 0xd0, 0x74, 0x64,
	0x05, 0xb0, 0x3b, 0xcf, 0x8a, 0x26, 0x56, 0x71, 0xe5, 0x14, 0xc3, 0x0c, 0xd9, 0x85, 0x66, 0x37,
	0xb6, 0x17, 0xf0, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff, 0x60, 0xa6, 0x7f, 0xcd, 0x0f, 0x02, 0x00,
	0x00,
}
