// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package file

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Payment struct {
	WalletAddress        string   `protobuf:"bytes,1,opt,name=walletAddress,proto3" json:"walletAddress,omitempty"`
	Asset                int32    `protobuf:"varint,2,opt,name=asset,proto3" json:"asset,omitempty"`
	UnitPrice            uint64   `protobuf:"varint,3,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_357a04084c6525e3, []int{0}
}
func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (dst *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(dst, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

func (m *Payment) GetAsset() int32 {
	if m != nil {
		return m.Asset
	}
	return 0
}

func (m *Payment) GetUnitPrice() uint64 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

type File struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	BlockHashes          []string `protobuf:"bytes,2,rep,name=blockHashes,proto3" json:"blockHashes,omitempty"`
	Operation            int32    `protobuf:"varint,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Prefix               string   `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	ChunkSize            int32    `protobuf:"varint,5,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	PayInfo              *Payment `protobuf:"bytes,6,opt,name=payInfo,proto3" json:"payInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_357a04084c6525e3, []int{1}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *File) GetBlockHashes() []string {
	if m != nil {
		return m.BlockHashes
	}
	return nil
}

func (m *File) GetOperation() int32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func (m *File) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *File) GetChunkSize() int32 {
	if m != nil {
		return m.ChunkSize
	}
	return 0
}

func (m *File) GetPayInfo() *Payment {
	if m != nil {
		return m.PayInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*Payment)(nil), "file.Payment")
	proto.RegisterType((*File)(nil), "file.File")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_file_357a04084c6525e3) }

var fileDescriptor_file_357a04084c6525e3 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x49, 0x9b, 0xdd, 0xb2, 0x53, 0x7a, 0x19, 0x44, 0x72, 0xf0, 0x10, 0x8a, 0x60, 0x4e,
	0x3d, 0xe8, 0x13, 0x78, 0x11, 0xbd, 0x95, 0xf8, 0x04, 0xe9, 0x76, 0x96, 0x0d, 0x8d, 0xc9, 0x92,
	0xa4, 0x68, 0x7d, 0x33, 0xdf, 0x4e, 0x36, 0x5d, 0xad, 0xde, 0xe6, 0xff, 0x86, 0xff, 0x3b, 0xfc,
	0x00, 0x9d, 0x75, 0xb4, 0x19, 0x62, 0xc8, 0x01, 0xf9, 0x78, 0xaf, 0x5b, 0x58, 0x6c, 0xcd, 0xe9,
	0x8d, 0x7c, 0xc6, 0x5b, 0x58, 0xbd, 0x1b, 0xe7, 0x28, 0x3f, 0xee, 0xf7, 0x91, 0x52, 0x12, 0x4c,
	0x32, 0xd5, 0xe8, 0xff, 0x10, 0xaf, 0xa0, 0x32, 0x29, 0x51, 0x16, 0x33, 0xc9, 0x54, 0xa5, 0xcf,
	0x01, 0x6f, 0xa0, 0x39, 0x7a, 0x9b, 0xb7, 0xd1, 0xb6, 0x24, 0xe6, 0x92, 0x29, 0xae, 0x2f, 0x60,
	0xfd, 0xc5, 0x80, 0x3f, 0x59, 0x47, 0x88, 0xc0, 0x7b, 0x93, 0xfa, 0xc9, 0x5c, 0x6e, 0x94, 0xb0,
	0xdc, 0xb9, 0xd0, 0x1e, 0x9e, 0x4d, 0xea, 0x29, 0x89, 0x99, 0x9c, 0xab, 0x46, 0xff, 0x45, 0xa3,
	0x3c, 0x0c, 0x14, 0x4d, 0xb6, 0xc1, 0x17, 0x79, 0xa5, 0x2f, 0x00, 0xaf, 0xa1, 0x1e, 0x22, 0x75,
	0xf6, 0x43, 0xf0, 0x62, 0x9d, 0xd2, 0xd8, 0x6a, 0xfb, 0xa3, 0x3f, 0xbc, 0xda, 0x4f, 0x12, 0xd5,
	0xb9, 0xf5, 0x0b, 0xf0, 0x0e, 0x16, 0x83, 0x39, 0xbd, 0xf8, 0x2e, 0x88, 0x5a, 0x32, 0xb5, 0xbc,
	0x5f, 0x6d, 0xca, 0x36, 0xd3, 0x18, 0xfa, 0xe7, 0xbb, 0xab, 0xcb, 0x5a, 0x0f, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x18, 0x14, 0xd5, 0xd9, 0x3b, 0x01, 0x00, 0x00,
}
