// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package payment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Payment struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver             string   `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	PaymentId            int32    `protobuf:"varint,3,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	Asset                int32    `protobuf:"varint,4,opt,name=asset,proto3" json:"asset,omitempty"`
	UnitPrice            uint64   `protobuf:"varint,5,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	Amount               uint64   `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	FileHash             string   `protobuf:"bytes,7,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	BlockHash            string   `protobuf:"bytes,8,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_5e545c936dbcab34, []int{0}
}
func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (dst *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(dst, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Payment) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Payment) GetPaymentId() int32 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *Payment) GetAsset() int32 {
	if m != nil {
		return m.Asset
	}
	return 0
}

func (m *Payment) GetUnitPrice() uint64 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *Payment) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Payment) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *Payment) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func init() {
	proto.RegisterType((*Payment)(nil), "payment.Payment")
}

func init() { proto.RegisterFile("payment.proto", fileDescriptor_payment_5e545c936dbcab34) }

var fileDescriptor_payment_5e545c936dbcab34 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x4d, 0xaa, 0xc2, 0x30,
	0x14, 0x85, 0xc9, 0x7b, 0xfd, 0x0d, 0x38, 0x09, 0x22, 0x17, 0x71, 0x50, 0x1c, 0x75, 0xe4, 0xc4,
	0x4d, 0xe8, 0xac, 0x74, 0x07, 0x69, 0x7b, 0xc5, 0x60, 0x9b, 0x94, 0x24, 0x15, 0x5c, 0xae, 0x3b,
	0x91, 0xa4, 0xd1, 0xcc, 0xf2, 0x9d, 0x8f, 0x1c, 0xce, 0xa5, 0x9b, 0x99, 0xbf, 0x26, 0x94, 0xf6,
	0x34, 0x6b, 0x65, 0x15, 0xcb, 0x03, 0x1e, 0xdf, 0x84, 0xe6, 0xcd, 0xfa, 0x66, 0x3b, 0x9a, 0x19,
	0x94, 0x03, 0x6a, 0x20, 0x15, 0xa9, 0xcb, 0x36, 0x10, 0xdb, 0xd3, 0x42, 0x63, 0x8f, 0xe2, 0x89,
	0x1a, 0xfe, 0xbc, 0xf9, 0x31, 0x3b, 0xd0, 0x32, 0x54, 0x5d, 0x07, 0xf8, 0xaf, 0x48, 0x9d, 0xb6,
	0x31, 0x60, 0x5b, 0x9a, 0x72, 0x63, 0xd0, 0x42, 0xe2, 0xcd, 0x0a, 0xee, 0xcf, 0x22, 0x85, 0x6d,
	0xb4, 0xe8, 0x11, 0xd2, 0x8a, 0xd4, 0x49, 0x1b, 0x03, 0xb7, 0x82, 0x4f, 0x6a, 0x91, 0x16, 0x32,
	0xaf, 0x02, 0xb9, 0x15, 0x37, 0x31, 0xe2, 0x85, 0x9b, 0x3b, 0xe4, 0xeb, 0x8a, 0x2f, 0xbb, 0xc6,
	0x6e, 0x54, 0xfd, 0xc3, 0xcb, 0xc2, 0xcb, 0x18, 0x74, 0x99, 0xbf, 0xf9, 0xfc, 0x09, 0x00, 0x00,
	0xff, 0xff, 0xd2, 0xab, 0xa2, 0xc1, 0x04, 0x01, 0x00, 0x00,
}
