// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payment struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver             string   `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	PaymentId            int32    `protobuf:"varint,3,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	Asset                int32    `protobuf:"varint,4,opt,name=asset,proto3" json:"asset,omitempty"`
	UnitPrice            uint64   `protobuf:"varint,5,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	Amount               uint64   `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	FileHash             string   `protobuf:"bytes,7,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	BlockHash            string   `protobuf:"bytes,8,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	TxHash               string   `protobuf:"bytes,9,opt,name=txHash,proto3" json:"txHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Payment) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Payment) GetPaymentId() int32 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *Payment) GetAsset() int32 {
	if m != nil {
		return m.Asset
	}
	return 0
}

func (m *Payment) GetUnitPrice() uint64 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *Payment) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Payment) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *Payment) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Payment) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func init() {
	proto.RegisterType((*Payment)(nil), "payment.Payment")
}

func init() { proto.RegisterFile("payment.proto", fileDescriptor_6362648dfa63d410) }

var fileDescriptor_6362648dfa63d410 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xcd, 0x8e, 0xc2, 0x20,
	0x14, 0x85, 0xc3, 0x4c, 0x7f, 0x49, 0x66, 0x43, 0x26, 0x86, 0x18, 0x17, 0x8d, 0xab, 0xae, 0xdc,
	0xf8, 0x12, 0xba, 0x6b, 0xfa, 0x06, 0xb4, 0xbd, 0x46, 0x62, 0x0b, 0x0d, 0x50, 0xa3, 0x8f, 0xee,
	0xce, 0x70, 0x41, 0xbb, 0xe3, 0x3b, 0x5f, 0x38, 0x39, 0x40, 0xff, 0x66, 0xf1, 0x9c, 0x40, 0xb9,
	0xc3, 0x6c, 0xb4, 0xd3, 0x2c, 0x8f, 0xb8, 0x7f, 0x11, 0x9a, 0x37, 0xe1, 0xcc, 0x36, 0x34, 0xb3,
	0xa0, 0x06, 0x30, 0x9c, 0x54, 0xa4, 0x2e, 0xdb, 0x48, 0x6c, 0x4b, 0x0b, 0x03, 0x3d, 0xc8, 0x3b,
	0x18, 0xfe, 0x83, 0xe6, 0xcb, 0x6c, 0x47, 0xcb, 0x58, 0x75, 0x1e, 0xf8, 0x6f, 0x45, 0xea, 0xb4,
	0x5d, 0x03, 0xf6, 0x4f, 0x53, 0x61, 0x2d, 0x38, 0x9e, 0xa0, 0x09, 0xe0, 0xef, 0x2c, 0x4a, 0xba,
	0xc6, 0xc8, 0x1e, 0x78, 0x5a, 0x91, 0x3a, 0x69, 0xd7, 0xc0, 0xaf, 0x10, 0x93, 0x5e, 0x94, 0xe3,
	0x19, 0xaa, 0x48, 0x7e, 0xc5, 0x45, 0x8e, 0x70, 0x12, 0xf6, 0xca, 0xf3, 0xb0, 0xe2, 0xc3, 0xbe,
	0xb1, 0x1b, 0x75, 0x7f, 0x43, 0x59, 0xa0, 0x5c, 0x03, 0xdf, 0xe8, 0x1e, 0xa8, 0xca, 0xf0, 0xae,
	0x40, 0x5d, 0x86, 0x7f, 0x71, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x42, 0x05, 0x5c, 0x8e, 0x1c,
	0x01, 0x00, 0x00,
}
