// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block_flights.proto

package block

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockFlights struct {
	TimeStamp            int64    `protobuf:"varint,1,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	PaymentId            int32    `protobuf:"varint,2,opt,name=PaymentId,proto3" json:"PaymentId,omitempty"`
	Blocks               []*Block `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockFlights) Reset()         { *m = BlockFlights{} }
func (m *BlockFlights) String() string { return proto.CompactTextString(m) }
func (*BlockFlights) ProtoMessage()    {}
func (*BlockFlights) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_flights_6d9b902e764ec992, []int{0}
}
func (m *BlockFlights) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockFlights.Unmarshal(m, b)
}
func (m *BlockFlights) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockFlights.Marshal(b, m, deterministic)
}
func (dst *BlockFlights) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockFlights.Merge(dst, src)
}
func (m *BlockFlights) XXX_Size() int {
	return xxx_messageInfo_BlockFlights.Size(m)
}
func (m *BlockFlights) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockFlights.DiscardUnknown(m)
}

var xxx_messageInfo_BlockFlights proto.InternalMessageInfo

func (m *BlockFlights) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *BlockFlights) GetPaymentId() int32 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *BlockFlights) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockFlights)(nil), "block.BlockFlights")
}

func init() { proto.RegisterFile("block_flights.proto", fileDescriptor_block_flights_6d9b902e764ec992) }

var fileDescriptor_block_flights_6d9b902e764ec992 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xca, 0xc9, 0x4f,
	0xce, 0x8e, 0x4f, 0xcb, 0xc9, 0x4c, 0xcf, 0x28, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x05, 0x0b, 0x4a, 0x71, 0x83, 0x29, 0x88, 0x98, 0x52, 0x01, 0x17, 0x8f, 0x13, 0x88, 0xeb,
	0x06, 0x51, 0x29, 0x24, 0xc3, 0xc5, 0x19, 0x92, 0x99, 0x9b, 0x1a, 0x5c, 0x92, 0x98, 0x5b, 0x20,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1c, 0x84, 0x10, 0x00, 0xc9, 0x06, 0x24, 0x56, 0xe6, 0xa6, 0xe6,
	0x95, 0x78, 0xa6, 0x48, 0x30, 0x29, 0x30, 0x6a, 0xb0, 0x06, 0x21, 0x04, 0x84, 0x54, 0xb8, 0xd8,
	0xc0, 0x46, 0x17, 0x4b, 0x30, 0x2b, 0x30, 0x6b, 0x70, 0x1b, 0xf1, 0xe8, 0x41, 0x6c, 0x02, 0x5b,
	0x10, 0x04, 0x95, 0x4b, 0x62, 0x03, 0x5b, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x17, 0x61,
	0x58, 0x4f, 0xa3, 0x00, 0x00, 0x00,
}
