// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block/block.proto

package block

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import payment "github.com/oniio/dsp-go-sdk/network/message/types/payment"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	Index                int32            `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	FileHash             string           `protobuf:"bytes,2,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	Hash                 string           `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Data                 []byte           `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Tag                  []byte           `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Operation            int32            `protobuf:"varint,6,opt,name=operation,proto3" json:"operation,omitempty"`
	Offset               int64            `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	Payment              *payment.Payment `protobuf:"bytes,8,opt,name=payment,proto3" json:"payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_42d1f3b77b1c0b86, []int{0}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Block) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetTag() []byte {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *Block) GetOperation() int32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func (m *Block) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Block) GetPayment() *payment.Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func init() {
	proto.RegisterType((*Block)(nil), "block.Block")
}

func init() { proto.RegisterFile("block/block.proto", fileDescriptor_block_42d1f3b77b1c0b86) }

var fileDescriptor_block_42d1f3b77b1c0b86 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xcf, 0x4e, 0x84, 0x30,
	0x10, 0xc6, 0x53, 0xa1, 0xfc, 0x19, 0x35, 0xc1, 0x89, 0x31, 0x0d, 0xf1, 0xd0, 0x78, 0x6a, 0x3c,
	0x60, 0xa2, 0x6f, 0xe0, 0xc9, 0xa3, 0xe9, 0x1b, 0x14, 0x29, 0x42, 0x44, 0x4a, 0xa0, 0x87, 0xdd,
	0x07, 0xdd, 0xf7, 0xd9, 0x74, 0x80, 0xdd, 0x4b, 0xfb, 0xfd, 0x7e, 0x6d, 0x32, 0xf3, 0xc1, 0x43,
	0x3d, 0xb8, 0x9f, 0xbf, 0x37, 0x3a, 0xab, 0x69, 0x76, 0xde, 0x21, 0x27, 0x28, 0xef, 0x27, 0x73,
	0xfc, 0xb7, 0xa3, 0x5f, 0xed, 0xcb, 0x89, 0x01, 0xff, 0x0c, 0x0f, 0xf8, 0x08, 0xbc, 0x1f, 0x1b,
	0x7b, 0x10, 0x4c, 0x32, 0xc5, 0xf5, 0x0a, 0x58, 0x42, 0xd6, 0xf6, 0x83, 0xfd, 0x32, 0x4b, 0x27,
	0x6e, 0x24, 0x53, 0xb9, 0xbe, 0x30, 0x22, 0xc4, 0x5d, 0xf0, 0x11, 0x79, 0xca, 0xc1, 0x35, 0xc6,
	0x1b, 0x11, 0x4b, 0xa6, 0xee, 0x34, 0x65, 0x2c, 0x20, 0xf2, 0xe6, 0x57, 0x70, 0x52, 0x21, 0xe2,
	0x33, 0xe4, 0x6e, 0xb2, 0xb3, 0xf1, 0xbd, 0x1b, 0x45, 0x42, 0xf3, 0xae, 0x02, 0x9f, 0x20, 0x71,
	0x6d, 0xbb, 0x58, 0x2f, 0x52, 0xc9, 0x54, 0xa4, 0x37, 0xc2, 0x57, 0x48, 0xb7, 0xe5, 0x45, 0x26,
	0x99, 0xba, 0x7d, 0x2f, 0xaa, 0xbd, 0xcc, 0xf7, 0x7a, 0xeb, 0xfd, 0x43, 0x9d, 0x50, 0xbd, 0x8f,
	0x73, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0x2e, 0x6d, 0x57, 0x09, 0x01, 0x00, 0x00,
}
